version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nextjs
    networks:
      - shared_network
    volumes:
      - next_export:/app/out
    deploy:
      resources:
        limits:
          memory: 384M

networks:
  shared_network:
    driver: bridge

volumes:
  next_export:
