version: '3'

services:
  app:
    restart: always
    memory: 400m
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    container_name: nextjs
    ports:
      - '3000:3000'
    networks:
      - shared_network
    volumes:
      - next_export:/app/out

networks:
  shared_network:
    driver: bridge

volumes:
  next_export:
