version: '3'

services:
  app:
    restart: always
    memory: 512m
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    container_name: nextjs
    ports:
      - '3000:3000'
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
